[package]
name = "rsa_rust"
version = "0.1.0"
authors = ["Dusty Phillips <dusty@phillips.codes>"]

[dependencies]
rand = "^0.5"
num-bigint = {version="0.2", features=["rand"]}
num-traits = "0.2"
num-integer = "0.1"
